version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: biblioteca_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: prestamolibros_db
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
