# Configuracion principal del proyecto de biblioteca

# Conexion MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/prestamolibros_db
spring.datasource.username=root
spring.datasource.password=
spring.flyway.baseline-on-migrate=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
server.port=8083

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.application.name=biblioteca

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Seguridad
app.security.user.name=admin
app.security.user.password=admin123
app.security.user.role=ADMIN
jwt.secret=VGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbnMtdGVjLWVkdQ==
jwt.expiration=3600000

# Logs
logging.level.root=INFO
logging.level.com.universidad.biblioteca=INFO
